#!/usr/bin/env bash
#script bonus

echo $$ > /var/run/myscript.pid

trap 'echo I hate the kill command' SEGTERM
trap 'echo Y U no love me?!' SIGINT
trap 'rm -rf /var/run/my.pid' SIGQUIT

while true
do
	echo "To infinity and beyond"
done

