#!/usr/bin/env bash

#print username + uid + home directory

while IFS=':' read -r user pass uid gid uid_info home shell
do
	echo "The user $user is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $pass, more info about the user here: $uid_info"
done < /etc/passwd
