#!/usr/bin/env bash
#print 10 times "Best School" at 4th occurence print "bad luck" and at 8 occurence print "good luck"

i=0

while [ $i -lt 10 ]
do
	if [ $i -eq 3 ]
	then
		echo "bad luck"
	elif [ $i -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	i=$(( i+1 ))
done

