#!/usr/bin/env bash
#print 20 times 1 to 20 at 4th occurence print "bad luck from China"
# at 9th occurence print "bad luck from Japan"
# ar 17th occurence print "bad luck from Italy"

i=1

while [ $i -le 20 ]
do
	echo $i
	if [ $i -eq 4 ]
	then
		echo "bad luck from China"
	elif [ $i -eq 9 ]
	then
		echo "bad luck from Japan"
	elif [ $i -eq 17 ]
	then
		echo "bad luck from Italy"
	fi
	i=$(( i+1 ))
done

